name: test-sdk
on:
  pull_request:
    branches:
      - main

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Start Anvil Fork
        run: anvil --fork-url ${{ secrets.SEPOLIA_RPC }} --port 8545 &

      - name: Wait for Anvil
        run: sleep 5

      - name: Run Tests
        run: pnpm test
